CREATE VIEW  SHAPEWITHPARAMETERS AS SELECT
DTYPE,
 ID,
 CREATED_AT,
CREATED_BY,
LAST_MODIFIED_AT,
LAST_MODIFIED_BY,
TYPE,VERSION,
SIDE,
WIDTH,
HEIGHT,
RADIUS,
CASE WHEN TYPE = 'CIRCLE' THEN  PI() * RADIUS * RADIUS
WHEN TYPE = 'RECTANGLE' THEN WIDTH * HEIGHT
When TYPE = 'SQUARE' THEN SIDE*SIDE
ELSE NULL
END AS area,
CASE
WHEN TYPE = 'CIRCLE' THEN 2 * PI() * RADIUS
WHEN TYPE = 'RECTANGLE' THEN 2 * (WIDTH + HEIGHT)
WHEN TYPE = 'SQUARE' THEN 4 * SIDE
ELSE NULL
END AS perimeter
FROM SHAPE
